### ISSUE TITLE
Does it support recognizing images that are not faces?

### ISSUE THREAD

**Issue by 1247862674** [HighwayWu/DeepFakeDefenders#12]

**Comment by HighwayWu** [comment]
Thank you for your asking.
- Due to the training data of this project being primarily focused on facial data for tasks like facial swap or editing, with only a portion involving full synthesis, I believe it may be challenging to apply it to detect non-facial or fully synthetic images.
- Nonetheless, you are welcome to test the detection on some general synthetic datasets such as [CNN-based Synthesis](https://github.com/PeterWang512/CNNDetection) and discuss the results with us.
